version: "3.0"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: TUES
#    volumes:
#      - ./db_data:/var/lib/postgresql/data  # To persist the data
